name: escape_wild
description: A text-based game powered by Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: 3.38.7

dependencies:
  flutter:
    sdk: flutter

  # I18n
  easy_localization: ^3.0.8
  locale_names: ^1.1.1

  # Basic
  collection: ^1.19.0
  json_annotation: ^4.9.0
  rettulf: ^3.0.0
  yaml: ^3.1.2
  path_provider: ^2.1.3
  event_bus: ^2.0.0
  quiver: ^3.2.1

  jconverter:
    git:
      url: https://github.com/liplum/DartPackage.git
      path: jconverter
  platform_safe_func:
    git:
      url: https://github.com/liplum/DartPackage.git
      path: platform_safe_func
  noitcelloc:
    git:
      url: https://github.com/liplum/noitcelloc.git

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2

  # UI
  flutter_layout_grid: ^2.0.6
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_sliders: ^31.2.10
  modal_bottom_sheet: ^3.0.0
  animations: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  flutter_highlight: ^0.7.0
  meta: ^1.15.0
  copy_with_extension: ^10.0.1
  uuid: ^4.5.1
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  tabler_icons: ^2.5.0+1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.9.3
  flutter_lints: ^6.0.0
  copy_with_extension_gen: ^10.0.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/l10n/
